# Generated by Django 3.0.3 on 2020-03-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_eventcategory_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventvenue',
            old_name='venure_name',
            new_name='venue_name',
        ),
    ]
